project:
  type: website

website:
  title: "Job Market Analysis 2025, Group 2"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Introduction"
      - href: data_analysis.qmd
        text: "Data Cleaning & Exploration"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd
        text: "ML Methods"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false 
    code-overflow: wrap