project:
  type: website

website:
  title: "Salary & Compensation Analytics; Group 2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research_introduction.qmd
        text: "Research Introduction"
      - href: data_analysis.qmd
        text: "Data Analysis"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



