---
title: "Skill Gap Analysis"
author:
  - name: Mahira Ayub
    affiliations:
      - id: bu
        name: Boston University
        city: Boston
        state: MA
  - name: Ava Godsy
    affiliations:
      - ref: bu
  - name: Joshua Lawrence
    affiliations:
      - ref: bu
format: 
  html:
    toc: true
---

```{python}
#| eval: false
#| echo: true 
import pandas as pd
df = pd.read_csv("data/lightcast_job_postings.csv")

filtered_df = df[["ID", "BODY"]]
filtered_df = filtered_df.dropna()
```

```{python}
#| eval: false
#| echo: true 
# Assuming job_descriptions is a list of text from job postings
top_skills = ["Python", "SQL", "Machine Learning", "Cloud Computing", "Docker", "AWS"]

skill_counts = {}
for skill in top_skills:
    skill_counts[skill] = filtered_df["BODY"].str.contains(skill, case=False, na=False).sum()

skills_df_pd = pd.DataFrame(list(skill_counts.items()), columns=['Skill', 'Count'])

print(skills_df_pd)
skills_df_pd.to_csv("data/skills_job_description.csv", index=False)
```

```{python}
#| eval: false
#| echo: true 
import plotly.express as px

top_skills_fig = px.bar(
    skills_df_pd,
    x='Skill',
    y='Count',
    title='Bar Chart of Job Description Skill Occurence',
    color_discrete_sequence=['#3D7C6A']  # Set bar color
)

# Update layout for fonts and sizes
top_skills_fig.update_layout(
    font=dict(
        family="Verdana",
        size=14,
        color="black"
    ),
    title=dict(
        font=dict(
            family="Verdana",
            size=18,
            color="black"
        )
    ),
    xaxis=dict(
        title_font=dict(
            family="Verdana",
            size=14,
            color="black"
        )
    ),
    yaxis=dict(
        title_font=dict(
            family="Verdana",
            size=14,
            color="black"
        )
    )
)

top_skills_fig.show()
top_skills_fig.write_image("figures/top_skills.png")
top_skills_fig.write_html("figures/top_skills.html")

```

#  Which skills should each member prioritize learning? 

- Based on the self assessment rating of each member of the group, everyone should prioritize learning cloud computing. 
- Cloud Computing is gaining popularity as data is moving to the cloud. Most companies are using cloud services to have easy access to data globally and in real time.

# What courses or resources can help?

- The resources and courses that can be helpful in learning cloud computing skills include:
  - Google Cloud Fundamentals
  - AWS Academy Cloud Foundations
  - Microsoft Learn - Azure Fundamentals
  - AWS Certified Data Analytics – Specialty
  - Azure Data Fundamentals (DP-900)

# How can the team collaborate to bridge skill gaps? 

- Identify gaps that are related to the project needs and work on it as a group to learn from eachother.
- Split tasks and divide work according to each memeber's skill level. 
- Cross-train so everyone can learn from each other and develop understanding of cloud analytics tasks. 
