---
title: "Research Introduction: AI vs. Non-AI Careers"
author: "Group 2"
date: today
format: 
  html:
    bibliography: references.bib
    csl: csl/econometrica.csl
    toc: true
---
## Introduction
It is no secret that AI has grown tremendously in availability and impact over the last few years. Students and professionals alike have experienced a rapid indoctrination of AI, whether that be as a simple end-user of ChatGPT or a developer of machine learning models. Being able to understand and adopt these technologies will be indispensable for all industries, and furthermore, open the door to more opportunities with higher compensation.\
\
As Applied Business Analytics students, we understand the importance of not only computer science knowledge, but the application of that knowledge to broader organizational understanding. The following literature review outlines the differences between salaries for AI vs. non-AI careers, regional differences, remote job salary comparisons, and industry comparisons.

## Literature Review
In this report, researchers Alekseeva et. al. (@Alekseeva_Azar_Giné_Samila_Taska_2021) recapped their findings of the demand for AI skills in the U.S. economy. The authors point out that it can be difficult to find data regarding companies’ demand for AI skills, so they used job posting data. They defined AI job postings as those that included “artificial intelligence”, “machine vision”, “deep learning” or “speech recognition”. They found that larger firms (measured by market capitalization, cash holdings, and investments in R&D) tended to pay more of a premium for AI skills. Firms with more demand for AI skills also offered high salaries in non-AI jobs than firms with less demand for AI skills.\
\
The results also showed that while IT-related industries have the highest demand for AI skills, there is significant growth across a wide range of industries outside of IT as well. Across all industries, AI skills hold an average of an 11% wage premium. The job with the largest premium is Management; the authors surmise that this means AI has the greatest value when combined with organizational knowledge.\
\
Authors Pabilonia and Vernon outline differences in compensation for remote and in-office roles (@Pabilonia_Vernon_2025). Using data from American Time Use Survey (ATUS) they note that remote work has increased in the US since 2020  (causal connection with the COVID-19 pandemic), and importantly “remote workers in most occupations earned a wage premium”. The authors performed extensive mathematical analysis within the paper, determining that in 2021 there was a 13.3% premium for remote work versus in-office work. Wages within the paper are indicated as being “determined by a number of factors, including job tasks, productivity differences, compensating differentials for job amenities, search frictions, and monopsony power, among others”. The authors also touched on disparity in pay within the principal city of the large metropolitan statistical area (MSA), noting that the wage premium for individuals working within the MSA was smaller (12.6%) than those working outside the 15 largest MDAs (14.5%). \
\
Card et. al. (@NBERw31587) discuss the locale for the highest paid jobs within the US. Unsurprisingly, using “data from the Longitudinal Employer-Household Dynamics program” the authors demonstrate connections between location and salary. Regions in major metropolitans and large industries have wage premiums up to 18% higher than national averages. The authors theorize that larger cities pay more due to their ability to attract and retain higher-skilled workers and the likely presence of large companies to support the talent. The authors do however also find that despite the higher wages in the major commuting zones (CZs), local costs “fully offset local pay premiums, implying that workers who move to larger CZs have no higher net-of-housing consumption”. This leads to the understanding that while more highly compensated in major metropolitan areas, the cost of living consumes the wage premium.\
\
According to the U.S. Bureau of Labor Statistics (BLS) (@bls2024projections), total employment is projected to grow by 4 percent between 2023 and 2033. There is also an expected increase in the number of jobs from 2023 to 2033 from 167.8 million to 17.46 million. Half of the forecasted job gains are expected to be in sectors such as healthcare, scientific and technical services. Whereas, the retail sector is more likely to lose jobs over the coming years.\
\
Industries that will see the most significant wage growth from 2023 and  2033 are those that will have a strong demand for specialized labor. Healthcare and social assistance jobs will see a rise in high paying roles such as nurse practitioners and physical therapists assistants. This sector will experience continued growth due to skill labor shortages and aging population. The scientific and technical services sector is expected to grow by 10.5% and it includes high paying roles such as software developers, cybersecurity professionals and data scientists. Renewable Energy industries sector will see an increase in jobs over the years as demand for photovoltaic installers and wind turbines service technicians is increasing and are expected to be hired at competitive rates.


## References